# Observium and MariaDB container
# Created by somsakc@hotmail.com
# Maintained by roccas@gmail.com

version: '3'

services:
  observiumdb:
       image: mariadb:latest
       environment:
         - MYSQL_ROOT_PASSWORD=passw0rd
         - MYSQL_USER=observium
         - MYSQL_PASSWORD=passw0rd
         - MYSQL_DATABASE=observium
         - TZ=America/Argentina/Mendoza
       volumes:
         - /home/docker/observium/data:/var/lib/mysql
#         - /home/docker/observium/mysql:/docker-entrypoint-initdb.d
       networks:
         - back-tier
       restart: always

  observiumap:
       build: observiumap
       environment:
         - OBSERVIUM_ADMIN_USER=admin
         - OBSERVIUM_ADMIN_PASS=passw0rd
         - OBSERVIUM_DB_HOST=observiumdb
         - OBSERVIUM_DB_NAME=observium
         - OBSERVIUM_DB_USER=observium 
         - OBSERVIUM_DB_PASS=passw0rd
         - OBSERVIUM_BASE_URL=http://changeme.host:8081
         - TZ=Europe/Oslo
       volumes:
         - /home/docker/observium/logs:/opt/observium/logs
         - /home/docker/observium/lock:/opt/observium/lock
         - /home/docker/observium/rrd:/opt/observium/rrd
       networks:
         - back-tier
       ports:
         - "8081:80"
       restart: always
       depends_on:
         - observiumdb

networks:
  back-tier:
      driver: bridge

