# Observium and MariaDB container

version: '3'

services:
  db:
       image: mariadb:latest
       environment:
         - MYSQL_ROOT_PASSWORD=passw0rd
         - MYSQL_USER=observium
         - MYSQL_PASSWORD=passw0rd
         - MYSQL_DATABASE=observium
         - TZ=Europe/Oslo
       volumes:
         - /home/docker/observium/data:/var/lib/mysql
#         - /home/docker/observium/mysql:/docker-entrypoint-initdb.d
       networks:
         - observium
       restart: always

  app:
       build: observiumap
       environment:
         - OBSERVIUM_ADMIN_USER=admin
         - OBSERVIUM_ADMIN_PASS=passw0rd
         - OBSERVIUM_DB_HOST=observiumdb
         - OBSERVIUM_DB_NAME=observium
         - OBSERVIUM_DB_USER=observium 
         - OBSERVIUM_DB_PASS=passw0rd
         - OBSERVIUM_BASE_URL=http://changeme.host:8081
         - TZ=Europe/Oslo
       volumes:
         - /home/docker/observium/logs:/opt/observium/logs
         - /home/docker/observium/lock:/opt/observium/lock
         - /home/docker/observium/rrd:/opt/observium/rrd
       networks:
         - observium
       ports:
         - "8081:80"
         - "514:514/udp"
       restart: always
       depends_on:
         - db

networks:
  observium:
      driver: bridge

